---
# tasks file for net

- name: Install Network software
  package:
    name:
        - nmap
        - zenmap
        - nmapsi4
        - youtube-dl
        - wget
        - aria2
        - mosh
        - tcpdump
        - wireshark
        - wireshark-gtk
        - wireshark-qt
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - openvpn
        - openvpn-systemd-resolved
        - whois
        - dnsutils
        - fwbuilder
        - ipcalc
        - sipcalc
        - mtr
        - speedtest-cli
        #- snort
        #- snort-doc
        #- snort-rules-default
    state: latest

- name: Install Dnsmasq
  package:
    name:
        - dnsmasq
        - dnsmasq-utils
    state: latest
 
- name: Install Nagstamon
  package:
    name:
        - nagstamon
    state: latest