- name: Install Network software
  package: name={{ item }} state=latest
  with_items:
    - nmap
    - zenmap
    - nmapsi4
    - youtube-dl
    - wget
    - aria2
    - mosh
    - tcpdump
    - wireshark
    - wireshark-gtk
    - wireshark-qt
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - openvpn
    - openvpn-systemd-resolved
    - whois
    - dnsutils
#    - snort
#    - snort-doc
#    - snort-rules-default

- name: Install Dnsmasq
  package: name={{ item }} state=latest
  with_items:
    - dnsmasq
    - dnsmasq-utils
 
