##  packages

- name: Install Thunderbird
  become: True
  apt: name={{ item }} state=latest
  with_items:
     - thunderbird
     - thunderbird-l10n-fr
     - calendar-exchange-provider
     - calendar-google-provider
     - enigmail
     - xul-ext-adblock-plus
     - xul-ext-adblock-plus-element-hiding-helper
     - xul-ext-https-everywhere
     - xul-ext-timeline
     - lightning
     - lightning-l10n-fr

- name: Install aspell
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - aspell
    - aspell-en
    - aspell-fr
