##  packages

- name: Install Thunderbird
  become: True
  apt: name={{ item }} state=latest
  with_items:
     - thunderbird
     - thunderbird-l10n-fr
     - calendar-google-provider
     - enigmail
     - webext-ublock-origin
     - webext-https-everywhere
     - xul-ext-timeline
     - xul-ext-gcontactsync
     - lightning
     - lightning-l10n-fr
# - calendar-exchange-provider xul-ext-adblock-plus xul-ext-adblock-plus-element-hiding-helper

- name: Install aspell
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - aspell
    - aspell-en
    - aspell-fr
