## Apt packages

- name: Configure APT sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list
  notify: apt update

- name: Install APT Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - tasksel
    - apt-clone
    - apt-file
    - aptitude
    - synaptic
    - aptitude-robot
    - apt-utils
    - netselect-apt
    - apt-transport-https
    - debian-archive-keyring
    - ca-certificates
    - gnupg2
    - software-properties-common

- name: Install Ansible Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - clamav
    - clamav-base
    - clamav-daemon
    - clamav-freshclam
    - clamav-testfiles
    - clamdscan
    - clamtk
    - clamtk-gnome
    - clamtk-nautilus


- name: Install Ansible Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - ansible-tower-cli

- name: Install Shell and System Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - htop
    - mssh
    - bash-completion
    - clusterssh
    - command-not-found
    - sudo
    - rsync

- name: Install Crypt Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - cryptmount
    - cryptsetup

- name: Install Irssi Tools
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - irssi
    - irssi-plugin-otr
    - irssi-plugin-robustirc
    - irssi-plugin-xmpp
    - irssi-scripts

- name: Install plymouth
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - plymouth
    - plymouth-theme-hamara
    - plymouth-themes

- include: debian-multimedia-repo.yml
- include: docker-ce-repo.yml
#- include: dropbox-repo.yml
- include: google-repo.yml
- include: opera-repo.yml
- include: vivaldi-repo.yml
