---
# tasks file for system

- name: Configure APT sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list
  notify: apt update

- name: Install APT Tools
  become: True
  package:
    name:
        - tasksel
        - apt-clone
        - apt-file
        - aptitude
        - synaptic
        - aptitude-robot
        - apt-utils
        - netselect-apt
        - apt-transport-https
        - debian-archive-keyring
        - ca-certificates
        - gnupg2
        - software-properties-common
        - screen
    state: latest

- name: Install Antivirus Tools
  become: True
  package:
    name:
        - clamav
        - clamav-base
        - clamav-daemon
        - clamav-freshclam
        - clamav-testfiles
        - clamdscan
        - clamtk
        - clamtk-gnome
        - clamtk-nautilus
    state: latest

- name: Install Shell, System Tools and Diags Tools
  become: True
  package:
    name:
        - htop
        - mssh
        - bash-completion
        - clusterssh
        - command-not-found
        - sudo
        - rsync
        - lshw
        - sysstat
        - ifstat
        - iotop
        - mtr
    state: latest
 
- name: Install Ansible Tools
  become: True
  package:
    name:
        - ansible-tower-cli
    state: latest

- name: Install Crypt Tools
  become: True
  package:
    name:
        - cryptmount
        - cryptsetup
    state: latest

- name: Install Irssi Tools
  become: True
  package:
    name:
        - irssi
        - irssi-plugin-otr
        - irssi-plugin-robustirc
        - irssi-plugin-xmpp
        - irssi-scripts
    state: latest

- name: Install plymouth
  become: True
  package:
    name:
        - plymouth
        - plymouth-theme-hamara
        - plymouth-themes
    state: latest

- name: Install Compression Tools
  become: True
  package:
    name:
        - unace
        - unace-nonfree
        - unrar-free
        - unrar
        - pigz
    state: latest

- name: Install Xmllint
  become: True
  package:
    name:
        - libxml2-utils
    state: latest

- name: Install Lynx
  become: True
  package:
    name:
        - lynx
    state: latest

- name: Install Mount Tools
  become: True
  package:
    name:
        - smbclient
        - smbnetfs
    state: latest

- include: debian-multimedia-repo.yml
- include: docker-ce-repo.yml
#- include: dropbox-repo.yml
- include: google-repo.yml
- include: opera-repo.yml
- include: vivaldi-repo.yml
- include: microsoft-vscode-repo.yml
- include: debian-backports-repo.yml

- name: Install Docker-CE
  become: True
  package:
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    state: latest