## Opera browsers Repo

- name: Install Opera Public Key
  apt_key:
    url: https://deb.opera.com/archive.key
    state: present

- name: Add Opera Repo
  become: True
  apt_repository:
   repo: deb https://deb.opera.com/opera-stable/ stable non-free
   state: present
   filename: 'opera-stable'
