## Tor browsers packages

- name: Install Tor
  become: True
  apt: name={{ item }} state=latest
  with_items:
    - tor
    - tor-geoipdb
    - torsocks

- name: Install Torbrowser Launcher
  become: True
  apt: name={{ item }} state=latest default_release={{ ansible_distribution_release }}-backports
  with_items:
    - torbrowser-launcher

