## Tor browsers packages

- name: Install Tor
  become: True
  package:
    name:
    - tor
    - tor-geoipdb
    - torsocks

- name: Install Torbrowser Launcher
  become: True
  package:
    name: 
        - torbrowser-launcher
    state: latest
    default_release: '{{ ansible_distribution_release }}-backports'

